repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.78.0
    hooks:
      - id: trufflehog
        name: TruffleHog (Scan for secrets)
        args: [--only-verified]

  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.108
    hooks:
      - id: checkov
        name: Checkov (IaC static analysis)